name: CI Pipeline

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install pytest
        
    - name: Configure CMake
      shell: cmd
      run: |
        cmake -S . -B build -G "Visual Studio 17 2022" -A x64
        
    - name: Build
      shell: cmd
      run: |
        cmake --build build --config Release
        
    - name: Run C++ tests
      shell: cmd
      run: |
        cd build && ctest -C Release --output-on-failure
        
    - name: Run Python tests
      shell: cmd
      run: |
        python -m pytest tests/python
        
    - name: Generate coverage report
      if: runner.os == 'Linux'
      run: |
        cd build
        lcov --capture --directory . --output-file coverage.info
        lcov --remove coverage.info '/usr/*' --output-file coverage.info
        bash <(curl -s https://codecov.io/bash) -f coverage.info